// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using clumsyapparel.Data;

#nullable disable

namespace ClumsyApparel.Migrations
{
    [DbContext(typeof(clumsyapparelDbContext))]
    [Migration("20251010005621_MakeUpdatedOnNullable")]
    partial class MakeUpdatedOnNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("clumsyapparel.Models.OrderForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfErrors")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Fulfilled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("HoursLogged")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageURL")
                        .HasColumnType("text");

                    b.Property<bool>("NeededHelp")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ShirtType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VinylType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfErrors = 0,
                            CreatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5668),
                            Fulfilled = true,
                            HoursLogged = 1.5m,
                            NeededHelp = false,
                            Notes = "Smooth process.",
                            Price = 19.99m,
                            Rating = 5,
                            ShirtType = "Cotton Tee",
                            UpdatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5673),
                            VinylType = "Heat Transfer"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfErrors = 1,
                            CreatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5678),
                            Fulfilled = false,
                            HoursLogged = 2.0m,
                            NeededHelp = true,
                            Notes = "Got stuck with layering.",
                            Price = 35.50m,
                            Rating = 4,
                            ShirtType = "Hoodie",
                            UpdatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5678),
                            VinylType = "Glitter"
                        },
                        new
                        {
                            Id = 3,
                            AmountOfErrors = 0,
                            CreatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5681),
                            Fulfilled = true,
                            HoursLogged = 1.0m,
                            NeededHelp = false,
                            Notes = "Fastest one yet.",
                            Price = 15.00m,
                            Rating = 5,
                            ShirtType = "Tank Top",
                            UpdatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5681),
                            VinylType = "Matte"
                        },
                        new
                        {
                            Id = 4,
                            AmountOfErrors = 2,
                            CreatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5684),
                            Fulfilled = false,
                            HoursLogged = 2.5m,
                            NeededHelp = true,
                            Notes = "Cool effect but tricky alignment.",
                            Price = 28.75m,
                            Rating = 3,
                            ShirtType = "Long Sleeve",
                            UpdatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5684),
                            VinylType = "Holographic"
                        },
                        new
                        {
                            Id = 5,
                            AmountOfErrors = 0,
                            CreatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5686),
                            Fulfilled = true,
                            HoursLogged = 1.75m,
                            NeededHelp = false,
                            Notes = "Loved how it turned out.",
                            Price = 24.00m,
                            Rating = 4,
                            ShirtType = "Raglan",
                            UpdatedOn = new DateTime(2025, 10, 10, 0, 56, 21, 37, DateTimeKind.Utc).AddTicks(5687),
                            VinylType = "Foil"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
