// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clumsyapparel.Data;

#nullable disable

namespace ClumsyApparel.Migrations
{
    [DbContext(typeof(clumsyapparelDbContext))]
    [Migration("20260103023544_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("clumsyapparel.Models.OrderForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOfErrors")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fulfilled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoursLogged")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeededHelp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShirtType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("VinylType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrderForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfErrors = 0,
                            CreatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8719),
                            Fulfilled = true,
                            HoursLogged = 1.5m,
                            NeededHelp = false,
                            Notes = "Smooth process.",
                            Price = 19.99m,
                            Rating = 5,
                            ShirtType = "Cotton Tee",
                            UpdatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8720),
                            VinylType = "Heat Transfer"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfErrors = 1,
                            CreatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8727),
                            Fulfilled = false,
                            HoursLogged = 2.0m,
                            NeededHelp = true,
                            Notes = "Got stuck with layering.",
                            Price = 35.50m,
                            Rating = 4,
                            ShirtType = "Hoodie",
                            UpdatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8728),
                            VinylType = "Glitter"
                        },
                        new
                        {
                            Id = 3,
                            AmountOfErrors = 0,
                            CreatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8731),
                            Fulfilled = true,
                            HoursLogged = 1.0m,
                            NeededHelp = false,
                            Notes = "Fastest one yet.",
                            Price = 15.00m,
                            Rating = 5,
                            ShirtType = "Tank Top",
                            UpdatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8731),
                            VinylType = "Matte"
                        },
                        new
                        {
                            Id = 4,
                            AmountOfErrors = 2,
                            CreatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8734),
                            Fulfilled = false,
                            HoursLogged = 2.5m,
                            NeededHelp = true,
                            Notes = "Cool effect but tricky alignment.",
                            Price = 28.75m,
                            Rating = 3,
                            ShirtType = "Long Sleeve",
                            UpdatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8735),
                            VinylType = "Holographic"
                        },
                        new
                        {
                            Id = 5,
                            AmountOfErrors = 0,
                            CreatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8737),
                            Fulfilled = true,
                            HoursLogged = 1.75m,
                            NeededHelp = false,
                            Notes = "Loved how it turned out.",
                            Price = 24.00m,
                            Rating = 4,
                            ShirtType = "Raglan",
                            UpdatedOn = new DateTime(2026, 1, 3, 2, 35, 44, 558, DateTimeKind.Utc).AddTicks(8738),
                            VinylType = "Foil"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
